version: '3'

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_DB = nextcloud
      - MYSQL_USER = spong
      - MYSQL_PASSWORD = 12345
      - MYSQL_HOST = lcoalhost
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITED --binlog-format=ROW
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = admin
      - MYSQL_PASSWORD = 12345
      - MYSQL_DATABASE = next
      - MYSQL_USER = bob

